/**
 * PHASE 5 — WORLD EVENT TYPES
 * 
 * Comprehensive event taxonomy for The Void world system.
 * All events are strongly typed and support analytics logging.
 */

export enum WorldEventType {
  // Player Lifecycle
  PLAYER_MOVED = "PLAYER_MOVED",
  USER_LOGGED_IN = "USER_LOGGED_IN",
  USER_LOGGED_OUT = "USER_LOGGED_OUT",
  
  // World Lifecycle
  WORLD_LOADED = "WORLD_LOADED",
  WORLD_UNLOADED = "WORLD_UNLOADED",
  
  // Parcel Events
  PARCEL_ENTERED = "PARCEL_ENTERED",
  PARCEL_EXITED = "PARCEL_EXITED",
  
  // District Events
  DISTRICT_ENTERED = "DISTRICT_ENTERED",
  DISTRICT_EXITED = "DISTRICT_EXITED",
  
  // Property Events (future expansion)
  PROPERTY_VIEWED = "PROPERTY_VIEWED",
  PROPERTY_PURCHASED = "PROPERTY_PURCHASED",
  
  // Discovery Events
  FIRST_PARCEL_VISIT = "FIRST_PARCEL_VISIT",
  FIRST_DISTRICT_VISIT = "FIRST_DISTRICT_VISIT",
  AREA_DISCOVERED = "AREA_DISCOVERED",
  
  // Session Events
  SESSION_STARTED = "SESSION_STARTED",
  SESSION_ENDED = "SESSION_ENDED",
  SESSION_HEARTBEAT = "SESSION_HEARTBEAT",
  
  // Interaction Events
  INTERACTABLE_HOVERED = "INTERACTABLE_HOVERED",
  INTERACTABLE_LEFT = "INTERACTABLE_LEFT",
  INTERACT_TRIGGERED = "INTERACT_TRIGGERED",
  INTERACTION_STARTED = "INTERACTION_STARTED",
  INTERACTION_COMPLETED = "INTERACTION_COMPLETED",
  INTERACTION_FAILED = "INTERACTION_FAILED",
  
  // XP Events (Phase 6.0)
  XP_GAINED = "XP_GAINED",
  XP_CAP_REACHED = "XP_CAP_REACHED",
  XP_MULTIPLIER_APPLIED = "XP_MULTIPLIER_APPLIED",
  
  // Achievement Events (Phase 6.1)
  ACHIEVEMENT_UNLOCKED = "ACHIEVEMENT_UNLOCKED",
  ACHIEVEMENT_PROGRESS = "ACHIEVEMENT_PROGRESS",
}

export type WorldEventTypes = `${WorldEventType}`;
